services:
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 20s
      retries: 3
    container_name: RabbitMQ
    ports:
      - "5672:5672"          # RabbitMQ main port
      - "15672:15672"        # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    
  consul:
    image : hashicorp/consul:latest
    container_name: Consul
    ports:
      - "8500:8500"
  
  apigateway:
    container_name: ApiGateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    restart: on-failure
    ports:
      - "5298:5298"
  
  userservice:
    container_name: UserService
    build:
      context: .
      dockerfile: UserService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "5038:5038"
  
  RestaurantService:
    container_name: RestaurantService
    build:
      context: .
      dockerfile: RestaurantService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "5048:5048"
  
  OrderService:
    container_name: OrderService
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    depends_on: 
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "5058:5058"