# This is a generated file. Not intended for manual editing.
services:
  courier-service:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0"
      dockerfile: "CourierService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CourierService.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "courierservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0\\CourierService:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  gateway:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0"
      dockerfile: "ApiGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ApiGateway.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "apigateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0\\ApiGateway:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  order-service:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0"
      dockerfile: "OrderService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/OrderService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "orderservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0\\OrderService:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  restaurant-service:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0"
      dockerfile: "RestaurantService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/RestaurantService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "restaurantservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0\\RestaurantService:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  user-service:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0"
      dockerfile: "UserService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/UserService.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "userservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0\\UserService:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\Food-delivery-Api-with .NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
